# Submits 25 test personas to the questionnaire endpoint.
# Reads persona data from seed-test-plans.js (the JS array is valid JSON-ish).
# Usage: powershell -File scripts/seed-test-plans.ps1

$SiteUrl = if ($env:SITE_URL) { $env:SITE_URL } else { "https://alongsideai.ai" }
$Endpoint = "$SiteUrl/.netlify/functions/submit-questionnaire"
$DelaySeconds = 5

# Build persona payloads inline (PowerShell hashtables).
$personas = @(
  @{ name="Frank"; situation="business"; comfort="basics"; work="I own three commercial rental properties in Pasadena. I handle everything - leases, maintenance requests, rent collection, bookkeeping. I've got a part-time property manager but she mostly handles showings and tenant calls."; creates="Leases, maintenance work orders, rent invoices, monthly owner statements, bank reconciliations"; team="partner"; typical_week="Mondays I review the financials and pay bills. Tuesday through Thursday I'm usually visiting properties or meeting with contractors. Fridays I try to catch up on paperwork but it always spills into Saturday."; location_today="mix"; location_wanted="Anywhere - I want to be able to handle urgent stuff from my phone when I'm on a job site or traveling."; devices="iphone, mac, ipad"; subscriptions="accounting, storage"; subscriptions_other="AppFolio for property management"; data_lives="QuickBooks Desktop on my office iMac, leases in a filing cabinet, tenant contact info split between my phone and AppFolio. Some stuff is in Google Drive but it's a mess."; tool_hated="QuickBooks Desktop"; tool_hated_why="I can't access it unless I'm sitting at my desk. Entering a bill takes fifteen clicks. The interface looks like it was designed in 2003 because it was."; friction="Keeping track of lease expirations, matching deposits to invoices, chasing late rent, paper everywhere. I spend half of Friday just looking for documents."; manual_tasks="1) Matching deposits to invoices in QuickBooks. 2) Sending the same intake email to every new tenant. 3) Manually updating a spreadsheet of lease dates."; already_tried="Tried to move to QuickBooks Online two years ago but my accountant said it couldn't handle the property reports I need. AppFolio helps but the accounting side is limited."; given_up_on="Having a clean, organized file system. I've tried Google Drive, Dropbox, even those paper organizer systems. Nothing sticks longer than a month."; inbox="overwhelmed"; inbox_note="I can never find that one email from the contractor two weeks ago. I get 80+ emails a day and maybe 10 matter."; wish="I wish I could work from anywhere and not be tied to my office computer. And I wish rent collection was completely hands-off."; explain_once="How I price a lease. Which contractors I trust for different jobs. Which tenants are good about paying on time and which ones need a reminder call on the 3rd. The rules about security deposits in California."; success_6mo="I'm spending winters somewhere warm. My property manager handles the inbox. Rent collects itself. I check a dashboard once a week instead of opening QuickBooks every day."; priority="time"; tried_ai="little"; nervous="I'm worried about putting tenant information - social security numbers, bank details - into these things. My attorney would have my head."; cloud_comfort="familiar"; urgency="asap"; budget_posture="100_250" },

  @{ name="Diane"; situation="business"; comfort="okay"; work="I run a boutique dental practice with four hygienists and two front desk staff. We see about 25 patients a day. I'm the only dentist."; creates="Treatment plans, patient communications, insurance claims, employee schedules, marketing emails to patients"; team="small"; typical_week="Patient care Mon-Thu 8am-5pm. Fridays are admin - payroll, ordering supplies, reviewing the books. One evening a week I try to write the monthly patient newsletter but I never finish it."; location_today="office"; location_wanted="I'd love to review the schedule and handle admin stuff from home in the morning before I drive in."; devices="iphone, pc"; subscriptions="m365, accounting, scheduling, email_marketing"; subscriptions_other="Dentrix for practice management, Weave for patient communications"; data_lives="Dentrix has all patient records. QuickBooks Online for bookkeeping. Staff schedule is an Excel file my office manager updates. Marketing stuff is in Constant Contact. Payroll is through ADP."; tool_hated="Constant Contact"; tool_hated_why="The email editor is clunky, templates look dated, and I can never figure out how to segment my list properly."; friction="Writing patient follow-up emails after consultations. Every one is slightly different but 80% the same. Also: insurance pre-authorization is pure paperwork torture."; manual_tasks="1) Writing individual follow-up emails after big treatment consultations. 2) Calling patients who haven't been in for 6+ months. 3) Manually entering supply orders into QuickBooks."; already_tried="My daughter set me up with a ChatGPT account. I used it a few times to draft emails but I kept forgetting to open it."; inbox="manageable"; wish="I wish I had a way to draft personalized patient emails that sound like me, not a robot, in about 30 seconds instead of 15 minutes."; explain_once="Our recall process. When to use which template. How I talk to nervous patients versus routine ones."; success_6mo="The newsletter goes out every month without me agonizing over it. Follow-up emails write themselves. I spend Friday afternoons doing something other than admin."; priority="time"; tried_ai="little"; nervous="HIPAA. That's the whole answer. Patient data cannot leave our systems."; cloud_comfort="nervous"; cloud_comfort_note="We're a healthcare practice. Everything has to be HIPAA-compliant."; urgency="month"; budget_posture="50_100" },

  @{ name="Carlos"; situation="business"; comfort="comfortable"; work="I own a landscaping company. 12 employees, mostly field crews. We do residential and commercial maintenance plus design-build projects."; creates="Estimates, invoices, contracts, job schedules, crew assignments, supply orders"; team="small"; typical_week="Monday morning I assign crews and review the week's jobs. Tues-Thurs I bounce between job sites and meeting with new clients for estimates. Friday is billing and payroll."; location_today="anywhere"; location_wanted="Same - but I want it to actually work instead of me juggling three apps on my phone in a truck."; devices="android, pc"; subscriptions="accounting, invoicing"; subscriptions_other="Jobber for scheduling and dispatch"; data_lives="Jobber has client info and job history. QuickBooks Online for finances. A lot of notes are just in text messages to my crews. Photos of completed work live in my phone gallery."; friction="Estimating takes forever. I'm driving to a site, measuring, then going home to type it all into Jobber. Half the time I forget a measurement and have to go back."; manual_tasks="1) Typing up estimates from handwritten notes. 2) Texting crew leads individual schedules every Monday morning. 3) Sorting job photos into client folders."; already_tried="We switched to Jobber last year and it helped a lot with scheduling. But the estimating is still slow."; inbox="manageable"; wish="I want to take a photo of a yard and get a rough estimate template back."; success_6mo="Estimates go out same day instead of three days later. My crews get their schedules automatically. I have an organized photo library of our work for proposals."; priority="money"; tried_ai="no"; nervous="Not really nervous - just haven't had time to look into it."; cloud_comfort="fine"; urgency="asap"; budget_posture="50_100" },

  @{ name="Patricia"; situation="business"; comfort="basics"; work="I run a small insurance agency. Independent - I represent about eight carriers. It's me and one admin assistant."; creates="Quotes, policy summaries, renewal letters, commission tracking spreadsheets, client birthday cards"; team="partner"; typical_week="Every day is client calls and quoting. Mondays are heavy on renewals. Wednesday afternoons I try to do marketing but I'm always behind."; location_today="office"; location_wanted="Home, mostly. My husband retired last year and I'd love to be more flexible."; devices="iphone, pc"; subscriptions="m365"; subscriptions_other="Hawksoft agency management system"; data_lives="Hawksoft has everything - client info, policy details, notes. But I also have a personal Excel spreadsheet with my commission tracking because Hawksoft's reports are terrible."; tool_hated="Hawksoft"; tool_hated_why="The interface is from the 90s. You can't access it from a browser. Reporting is so bad I maintain my own Excel sheets alongside it."; friction="Quoting. Each carrier has a different portal and I'm logging into five or six of them per quote, re-entering the same information each time. A single auto quote takes me 45 minutes."; manual_tasks="1) Re-entering client data into each carrier portal when quoting. 2) Updating my commission spreadsheet monthly. 3) Sending renewal reminder letters."; already_tried="Looked at EZLynx but the migration cost was $15,000."; given_up_on="Having a proper CRM. I use Hawksoft's contact list but it's not a real CRM."; inbox="overwhelmed"; inbox_note="Carriers email constantly. I miss important renewal notices in the flood."; wish="I wish quoting didn't require logging into six different websites."; explain_once="Which carriers are competitive for which types of policies. My preferred carriers by line of business. How I calculate commissions for each carrier."; success_6mo="Quoting takes 15 minutes instead of 45. I'm not maintaining a parallel spreadsheet. I can work from home two days a week."; priority="peace"; tried_ai="no"; nervous="Client financial information. Insurance applications have social security numbers, addresses, driver's license numbers."; cloud_comfort="nervous"; cloud_comfort_note="I have E&O insurance that requires certain data handling practices."; urgency="month"; budget_posture="100_250" },

  @{ name="Jim"; situation="business"; comfort="avoid"; work="General contractor. Residential remodels mostly - kitchens, bathrooms, additions. Been doing this 35 years."; creates="Estimates, change orders, subcontractor agreements, material lists, progress photos for clients"; team="solo"; typical_week="On job sites all day, every day. Evenings and weekends I do the paperwork. My wife helps with bookkeeping but she's tired of it."; location_today="anywhere"; location_wanted="Same. But I need the paperwork to be simpler."; devices="iphone, pc"; subscriptions="accounting"; data_lives="QuickBooks on the home computer. Estimates are in Word documents. Subcontractor contacts are in my phone. A lot of job details are just in my head."; friction="Writing estimates. I know what a kitchen remodel costs in my sleep but writing it all out formal-like takes me three hours."; manual_tasks="1) Writing up estimates from scratch each time. 2) Creating material lists for the lumber yard. 3) Taking photos on my phone and texting them one by one to clients."; already_tried="My son showed me some contractor estimating software. Too complicated."; inbox="surrendered"; wish="I just want someone or something to turn my rough notes into a professional-looking estimate."; success_6mo="Estimates go out the same day I visit a site instead of a week later. My wife stops doing bookkeeping on Sundays."; priority="time"; tried_ai="no"; nervous="I don't understand it and I don't trust what I don't understand."; cloud_comfort="local"; urgency="exploring"; budget_posture="under_50" },

  @{ name="Anita"; situation="business"; comfort="okay"; work="I own a bakery and cafe. We do walk-in retail, wholesale to two grocery chains, and catering for events. 8 employees."; creates="Inventory orders, catering proposals, social media posts, employee schedules"; team="small"; typical_week="I'm in the kitchen 4am-noon baking. Afternoons are orders, admin, and trying to keep up with Instagram. Saturday mornings are our busiest retail time."; location_today="office"; location_wanted="I'd like to handle admin from home in the afternoons."; devices="iphone, ipad, mac"; subscriptions="google, accounting, scheduling"; subscriptions_other="Square for POS, Later for social media scheduling"; data_lives="Square has all our sales data. QuickBooks Online for bookkeeping. Recipes are in binders. Wholesale client info is in a Google Sheet."; friction="Social media. I know it's important but creating posts, taking good photos, writing captions eats two hours a day."; manual_tasks="1) Writing Instagram captions and scheduling posts. 2) Creating weekly employee schedules. 3) Calculating ingredient quantities when scaling recipes for catering."; already_tried="Hired a social media manager for three months. She was great but $2,000/month wasn't sustainable."; inbox="manageable"; wish="I wish social media content could mostly create itself. I'll take the photos."; success_6mo="We're posting consistently without it consuming my afternoons. Catering proposals go out fast. I actually take Sundays off."; priority="mix"; tried_ai="little"; nervous="Not really. I tried ChatGPT for writing a catering menu description once and it was decent."; cloud_comfort="fine"; urgency="asap"; budget_posture="50_100" },

  @{ name="Robert"; situation="business"; comfort="basics"; work="Small consulting firm - management consulting for mid-size manufacturing companies. Three consultants plus me."; creates="Proposals, engagement letters, project status reports, slide decks, final deliverable reports (30-50 pages)"; team="small"; typical_week="Monday is internal. Tuesday through Thursday I'm at client sites or on calls. Friday is proposal writing and business development."; location_today="mix"; location_wanted="Flexible - I travel to clients in three states."; devices="iphone, pc, ipad"; subscriptions="m365, storage, crm"; subscriptions_other="HubSpot CRM free tier, Toggl for time tracking"; data_lives="OneDrive has project files. HubSpot has client contacts and pipeline. Time entries in Toggl. Proposals are Word docs. No consistent naming convention."; friction="Proposal writing. Every proposal is 60% the same but I rewrite from scratch because I can never find the right previous one to copy from."; manual_tasks="1) Writing proposals from scratch. 2) Compiling weekly status reports from each consultant's notes. 3) Logging time."; already_tried="Tried standardizing templates in SharePoint. It lasted about six weeks."; inbox="manageable"; inbox_note="Email is my main tool. I live in Outlook. But searching for old client emails is terrible."; wish="I want a proposal engine. Feed it the client, scope, and timeline - and get a first draft back that's 80% there."; success_6mo="Proposals go out in a day instead of a week. Status reports are consistent."; priority="money"; tried_ai="regular"; nervous="Client confidentiality. We work with companies that require NDAs."; cloud_comfort="fine"; cloud_comfort_note="Already cloud-native. Just need data privacy guarantees for client-sensitive material."; urgency="asap"; budget_posture="100_250" },

  @{ name="Linda"; situation="business"; comfort="basics"; work="I own a small retail gift shop in a tourist town. Just me and two part-time employees."; creates="Purchase orders, social media posts, a monthly email newsletter, basic bookkeeping entries"; team="partner"; typical_week="I'm in the shop most days. Mornings before we open I do ordering and bookkeeping. Afternoons are floor time."; location_today="office"; location_wanted="The shop - but I want to stop taking paperwork home at night."; devices="iphone, ipad"; subscriptions="accounting, email_marketing"; subscriptions_other="Shopify for online store, Square for in-store POS"; data_lives="Shopify has online orders. Square has in-store sales. QuickBooks has the bookkeeping. Vendor contacts are in my phone and a paper Rolodex."; friction="Keeping inventory synced between the physical shop and Shopify. I sell something in store and forget to update online, then sell it twice."; manual_tasks="1) Updating Shopify inventory after in-store sales. 2) Writing product descriptions for new items. 3) Reposting product photos from Instagram to Facebook."; already_tried="Shopify has a Square integration but it never worked right."; inbox="manageable"; wish="I wish product descriptions wrote themselves. I take a photo, it figures out what it is, and gives me a nice description."; success_6mo="Inventory is synced. Every product has a description. Social media posts go out regularly."; priority="peace"; tried_ai="no"; nervous="Not nervous exactly - more overwhelmed. I don't know where to start."; cloud_comfort="familiar"; urgency="month"; budget_posture="under_50" },

  @{ name="Margaret"; situation="semi_retired"; comfort="basics"; work="I was a corporate attorney for 30 years. Now I do occasional consulting - reviewing contracts, advising on governance. Maybe 10-15 hours a week."; creates="Contract redlines, advisory memos, emails to former colleagues"; team="solo"; typical_week="No fixed schedule. Some weeks I have three calls and a document to review. Other weeks nothing."; location_today="home"; location_wanted="Home and my daughter's house in Portland - I visit for weeks at a time."; devices="iphone, mac"; subscriptions="m365"; data_lives="Everything is in Word docs and email. Some files on my Mac desktop, some in OneDrive, some I can't find at all."; friction="Document management. I have hundreds of contract templates and I can never find the right one."; manual_tasks="1) Searching through folders for a relevant prior contract. 2) Reformatting documents when clients send me PDFs. 3) Tracking my hours."; already_tried="My former firm had a document management system. I looked at getting one but they all assume you have an IT department."; inbox="manageable"; wish="I wish I could say 'find me the last contract I reviewed for a software licensing deal' and have it just appear."; success_6mo="I can find any document in under 30 seconds. My advisory work is organized."; priority="peace"; tried_ai="little"; nervous="Attorney-client privilege. If client documents end up in some AI company's training data, I have a real liability problem."; cloud_comfort="nervous"; cloud_comfort_note="Attorney-client privilege is non-negotiable."; urgency="month"; budget_posture="50_100" },

  @{ name="Howard"; situation="semi_retired"; comfort="avoid"; work="Retired cardiologist. I still do peer review for two medical journals and volunteer at a free clinic one day a week."; creates="Peer review reports, some patient notes at the clinic, travel itineraries"; team="solo"; typical_week="Two or three journal articles to review per month. Clinic is every Thursday. Rest of the time reading, gardening, or planning trips."; location_today="home"; location_wanted="Wherever we're traveling. I review articles on planes all the time."; devices="iphone, ipad, mac"; subscriptions="storage"; data_lives="Email, mostly. Some files on my Mac. Journal articles pile up in my email inbox as PDF attachments."; friction="Managing the journal review process. I get PDFs by email, make notes on paper, type up the review, email it back."; manual_tasks="1) Printing PDFs to annotate by hand. 2) Typing up handwritten review notes. 3) Organizing travel documents."; inbox="overwhelmed"; wish="I want to annotate PDFs naturally and have it turn into a proper typed review."; success_6mo="Reviews are done digitally end-to-end, no printing. Travel documents are organized."; priority="time"; tried_ai="no"; nervous="I'm 72. I'm more worried about the learning curve than privacy."; cloud_comfort="familiar"; urgency="exploring"; budget_posture="under_50" },

  @{ name="Susan"; situation="semi_retired"; comfort="okay"; work="Former CFO. I still sit on two nonprofit boards and do fractional CFO work for a friend's startup about 10 hours a week."; creates="Board reports, financial analyses, cash flow forecasts, the occasional slide deck"; team="solo"; typical_week="Monday and Wednesday mornings on the startup's finances. Board meetings once a month each. Managing personal investments."; location_today="home"; location_wanted="Home and our cabin in Vermont."; devices="mac, iphone, ipad"; subscriptions="m365, google, accounting, storage"; data_lives="Google Drive for the startup. OneDrive for personal. QuickBooks Online for the startup and my husband's business."; friction="Building financial models. I used to have a team. Now I'm building Excel models from scratch and it takes all day."; manual_tasks="1) Rebuilding the same cash flow forecast template. 2) Pulling data from QuickBooks into Excel. 3) Formatting board reports."; already_tried="I've used ChatGPT for some formula help in Excel. It's surprisingly good at that."; inbox="zero"; wish="I want a financial analysis assistant that understands accounting."; success_6mo="Board reports are polished in half the time. The startup's monthly close takes two hours instead of six."; priority="time"; tried_ai="regular"; nervous="Financial data is sensitive - revenue numbers, compensation, runway projections."; cloud_comfort="fine"; urgency="asap"; budget_posture="100_250" },

  @{ name="George"; situation="semi_retired"; comfort="basics"; work="Retired school principal. Now I run a small educational consulting practice - helping schools with curriculum design and accreditation prep."; creates="Curriculum review reports, accreditation self-study documents, professional development presentations, grant narratives"; team="solo"; typical_week="Very flexible. Usually two or three client calls per week, plus writing time. I procrastinate on the writing."; location_today="home"; location_wanted="Home is great. Maybe a coffee shop sometimes."; devices="pc, iphone"; subscriptions="m365"; data_lives="OneDrive, mostly. But I have files going back 20 years on an external hard drive."; friction="Writing. I write well but slowly. A 40-page accreditation self-study takes me three weeks."; manual_tasks="1) Formatting documents to different accreditation body standards. 2) Searching through old reports for relevant language. 3) Creating slide decks for workshops."; inbox="manageable"; wish="I want a writing partner that knows education. Something that can take my outline and turn it into a solid first draft in my voice."; success_6mo="Reports take one week instead of three. I'm taking on one more client because I have the bandwidth."; priority="money"; tried_ai="little"; nervous="Accuracy. In education, if an AI makes something up it could damage my reputation."; cloud_comfort="fine"; urgency="month"; budget_posture="50_100" },

  @{ name="Deborah"; situation="semi_retired"; comfort="comfortable"; work="Was a marketing VP. Now I consult part-time for three small businesses on their marketing. About 20 hours a week."; creates="Marketing plans, social media content calendars, blog post drafts, email campaign copy, competitive analyses"; team="solo"; typical_week="Each client gets a half-day per week. The rest is content creation. I also run a small Substack newsletter."; location_today="home"; location_wanted="Home and my partner's place in Arizona."; devices="mac, iphone"; subscriptions="google, ai, email_marketing, scheduling"; subscriptions_other="Canva Pro, Buffer, Claude Pro"; data_lives="Google Drive organized by client. Canva has design assets. Content calendars are Google Sheets."; friction="Volume. Three clients each want 8-12 social media posts per week plus a blog post plus email campaigns."; manual_tasks="1) Repurposing one blog post into 5-6 social media posts. 2) Resizing graphics in Canva. 3) Compiling monthly analytics reports."; already_tried="I use Claude regularly for drafting. It's good but I want a more systematic workflow."; inbox="zero"; wish="I want a content production system. I write one strategic piece per client per week and everything else generates from that."; success_6mo="I'm spending 80% of my time on strategy and 20% on production. I could take a fourth client."; priority="money"; tried_ai="regular"; nervous="Not about AI itself - more about quality. My name is on this work."; cloud_comfort="fine"; urgency="asap"; budget_posture="100_250" },

  @{ name="Kevin"; situation="professional"; comfort="okay"; work="Regional sales manager for a building materials distributor. I manage 8 reps across three states. Lots of driving, lots of calls."; creates="Sales reports, expense reports, call summaries, quarterly business reviews, customer proposals"; team="small"; typical_week="Monday: team call, pipeline review. Tuesday-Thursday: customer visits, ride-alongs. Friday: reports, admin, forecasting. In the car 15+ hours a week."; location_today="anywhere"; location_wanted="The road. But I need mobile tools that actually work."; devices="iphone, pc"; subscriptions="m365, crm"; subscriptions_other="Salesforce (company-provided)"; data_lives="Salesforce has CRM data but it's badly maintained. Expense reports in Concur. Presentations in PowerPoint."; friction="CRM updates. After every customer visit I'm supposed to log notes and update opportunity stages. It takes 30 minutes per visit."; manual_tasks="1) Typing up CRM notes after customer visits. 2) Creating the weekly sales report. 3) Transcribing voice memos."; already_tried="Tried voice-to-text for CRM entries. The transcription was too messy."; inbox="overwhelmed"; inbox_note="200+ emails a day. My reps CC me on everything."; wish="I want to dictate a 2-minute voice memo and have it automatically become a CRM entry and an email follow-up."; success_6mo="CRM is always current without me typing anything. Weekly reports build themselves."; priority="time"; tried_ai="little"; nervous="Company data policy. I can't put customer info into tools our IT hasn't approved."; cloud_comfort="fine"; urgency="asap"; budget_posture="50_100" },

  @{ name="Rachel"; situation="professional"; comfort="comfortable"; work="Product manager at a mid-size SaaS company. I manage two product lines."; creates="PRDs, user stories, competitive analyses, roadmap decks, stakeholder update emails, sprint planning notes"; team="larger"; typical_week="Monday: sprint planning. Tuesday-Wednesday: customer calls, design reviews. Thursday: roadmap and strategy. Friday: stakeholder updates."; location_today="mix"; location_wanted="Same mix - office 2-3 days, home the rest."; devices="mac, iphone"; subscriptions="google, ai, project"; subscriptions_other="Notion, Linear, Figma, Loom"; data_lives="Notion has product specs. Linear has engineering tickets. Figma has designs. Customer feedback in Dovetail plus random Slack threads."; friction="Context switching. I'm in 25 meetings a week and every one generates follow-up tasks and documents."; manual_tasks="1) Writing meeting summaries and extracting action items. 2) Updating the roadmap deck. 3) Writing the weekly stakeholder email."; already_tried="I use Claude for drafting PRDs and it's great. But I haven't connected it to my actual workflows."; inbox="overwhelmed"; wish="I want my meetings to auto-generate summaries, action items, and the right Notion/Linear updates."; success_6mo="Meeting notes happen automatically. The roadmap deck is always current. I have Thursday for deep work every week."; priority="time"; tried_ai="regular"; nervous="Accuracy of summaries. If an AI misrepresents what was decided in a meeting, that creates real problems."; cloud_comfort="fine"; urgency="month"; budget_posture="50_100" },

  @{ name="Thomas"; situation="professional"; comfort="basics"; work="Architect at a small firm. Mostly residential - custom homes and renovations. One of three partners."; creates="Client presentations, design proposals, construction specifications, permit applications, project timelines"; team="small"; typical_week="Monday: partner meeting, project reviews. Tuesday-Thursday: design work, client meetings, site visits. Friday: admin, billing, proposals."; location_today="office"; location_wanted="I'd like to sketch ideas at home in the evenings."; devices="mac, iphone, ipad"; subscriptions="m365, storage"; subscriptions_other="AutoCAD, SketchUp Pro, Bluebeam"; data_lives="Project files on the firm's NAS drive. I can VPN in but it's slow. Client correspondence in Outlook. Sketches on iPad in Procreate."; friction="Specifications writing. Pages and pages of construction specs. 70% is boilerplate that I customize, but hunting through past specs takes forever."; manual_tasks="1) Assembling construction specifications from past projects. 2) Creating client presentation boards. 3) Tracking permit application status."; already_tried="We bought BSD SpecLink. It was overkill. Nobody used it."; inbox="manageable"; wish="I want a specification library that knows our firm's preferences."; success_6mo="Specs take a day instead of three. Client presentations come together in an afternoon. I leave by 6 instead of 8."; priority="time"; tried_ai="little"; nervous="Not particularly. I'd try anything that saves me from writing specs."; cloud_comfort="familiar"; urgency="month"; budget_posture="100_250" },

  @{ name="Priya"; situation="professional"; comfort="okay"; work="Nonprofit program director. I oversee three education programs for underserved youth. Small team, big mission, no budget."; creates="Grant proposals, program reports, donor update letters, impact metrics dashboards, board presentations"; team="small"; typical_week="Monday: team huddle. Tuesday-Thursday: program site visits, meetings with school partners. Friday: grant writing, reporting, donor emails."; location_today="mix"; location_wanted="Wherever - I'm at sites, the office, home, a coffee shop."; devices="mac, iphone"; subscriptions="google"; subscriptions_other="Salesforce NPSP free, Canva free tier"; data_lives="Google Drive for everything. Salesforce has donor info. Program data is in Google Sheets."; friction="Grant writing. I write 15-20 grants a year and each one takes 10-20 hours. They all ask the same information in slightly different ways."; manual_tasks="1) Rewriting the same program description for each grant. 2) Pulling impact data from multiple Google Sheets. 3) Creating the quarterly board report."; already_tried="We tried Instrumentl for grant discovery. Good for finding grants, terrible for writing them."; inbox="overwhelmed"; wish="I want a grant writing engine that knows our programs, our data, our boilerplate."; success_6mo="I'm submitting twice as many grants without working more hours. The board report takes an afternoon instead of two days."; priority="money"; tried_ai="little"; nervous="We serve minors. Student data has to stay private. FERPA applies."; cloud_comfort="fine"; cloud_comfort_note="We handle student data under FERPA."; urgency="asap"; budget_posture="under_50" },

  @{ name="Jason"; situation="helping"; comfort="comfortable"; work="I'm a software engineer. This isn't for me - it's for my mom. She's 68, retired teacher, lives alone. She has a small quilting business on Etsy."; creates="Etsy listings, customer messages, shipping labels, fabric inventory notes"; team="solo"; typical_week="She quilts most days. Etsy orders come in waves. She spends way too long on each listing."; location_today="home"; location_wanted="Home is fine for her. She just needs things to be simpler."; devices="iphone, ipad"; subscriptions="storage"; data_lives="Etsy has her orders and listings. Photos are on her iPad. She has a physical notebook where she tracks fabric inventory."; friction="Everything takes her 10x longer than it should. Writing an Etsy listing takes an hour. She types with one finger."; manual_tasks="1) Writing Etsy product descriptions. 2) Responding to customer questions - usually the same 5 questions. 3) Tracking fabric inventory in a notebook."; already_tried="I set her up with a Google Sheet for inventory. She used it for a week and went back to the notebook."; inbox="manageable"; wish="She takes a photo of a finished quilt, says a few words about it, and a listing appears on Etsy."; success_6mo="Mom is spending her time quilting, not fighting with her iPad. Listings go up quickly. She's enjoying the business."; priority="peace"; tried_ai="no"; nervous="She doesn't know what AI is. It has to be dead simple."; cloud_comfort="familiar"; urgency="month"; budget_posture="under_50" },

  @{ name="Michelle"; situation="helping"; comfort="okay"; work="Setting this up for my father-in-law, Ed. He's 74, retired executive. He manages a family rental property and volunteers as treasurer for his church."; creates="Rent receipts, church financial reports, donation acknowledgment letters, personal budget"; team="solo"; typical_week="He collects rent on the 1st with a paper receipt book. Church treasurer work is a few hours a week. He does everything in a ledger book."; location_today="home"; location_wanted="Home. He's not going anywhere else."; devices="ipad, pc"; data_lives="A ledger book. A filing cabinet. He has a PC but uses it for email and news. The church gave him QuickBooks but he's never opened it."; friction="The church books. He's meticulous but it's all by hand. Month-end takes him a full Saturday."; manual_tasks="1) Recording church donations by hand. 2) Writing donation acknowledgment letters. 3) Tracking rental income and expenses in a ledger."; already_tried="His daughter installed QuickBooks on his PC. He opened it once and closed it. Too many buttons."; inbox="manageable"; wish="He just wants the church reports to be done. Not fancy - just typed up and correct."; success_6mo="The church gets clean monthly reports. Donation letters go out on time. Ed feels competent."; priority="peace"; tried_ai="no"; nervous="He doesn't trust the computer with financial information. This has to feel safe and familiar."; cloud_comfort="local"; urgency="exploring"; budget_posture="under_50" },

  @{ name="Stephanie"; situation="helping"; comfort="comfortable"; work="This is for my parents. Dad is 71, semi-retired accountant. Mom is 69, runs the household and manages their rental condo in Florida."; creates="Tax returns (dad), rental property records (mom), family schedule coordination, photo organization"; team="partner"; typical_week="Dad works on tax stuff maybe 10 hours a week during season. Mom handles the Florida rental - booking, cleaning schedules, guest communication."; location_today="home"; location_wanted="They want to snowbird. Spend winters in Florida. But dad says he can't because Drake is on the desktop at home."; devices="iphone, pc, ipad"; subscriptions="m365"; subscriptions_other="Drake tax software (dad), Vrbo listing (mom)"; data_lives="Drake has all tax files on dad's PC. Mom's rental records are in a folder on the kitchen counter."; friction="Dad can't work remotely at all. Mom spends hours coordinating cleaners, sending check-in instructions, responding to the same guest questions."; manual_tasks="1) Mom manually sends check-in instructions to each Vrbo guest. 2) Dad manually enters data from paper tax documents. 3) Mom keeps a paper calendar of rental bookings."; already_tried="I got them an iPad thinking it would be easier. They use it for email and Sudoku."; inbox="manageable"; wish="For dad: work from anywhere. For mom: the rental runs itself - guests get instructions automatically."; success_6mo="They're in Florida for the winter. Dad's handling tax season from the condo. Mom's rental management takes 30 minutes a week."; priority="peace"; tried_ai="no"; nervous="Dad has tax returns with social security numbers. Whatever we do has to keep that data local or in something he trusts."; cloud_comfort="nervous"; cloud_comfort_note="Dad handles taxpayer SSNs. Mom is fine with cloud for rental stuff."; urgency="asap"; budget_posture="50_100" },

  @{ name="Walter"; situation="retired"; comfort="basics"; work="Fully retired mechanical engineer. President of my HOA board, volunteer at the local history museum, and trying to write a book about industrial history."; creates="HOA meeting minutes, museum volunteer schedules, book manuscript chapters, research notes"; team="solo"; typical_week="Museum two mornings a week. HOA stuff pops up randomly. Book research and writing whenever I can fit it in."; location_today="home"; location_wanted="Home. The library when researching."; devices="pc, iphone"; subscriptions="m365"; data_lives="Word documents everywhere. Some on the PC desktop, some in Documents, some on a USB drive. Research notes in notebooks."; friction="Organizing research. I have stacks of photocopied documents, scanned photos, interview notes. None of it is organized or searchable."; manual_tasks="1) Typing up handwritten research notes. 2) Formatting HOA meeting minutes. 3) Creating the museum volunteer schedule."; already_tried="My grandson set up Evernote for me. I used it for a month. Then I forgot my password."; inbox="manageable"; wish="I want all my research to be searchable. Scan a document and find it later by what it says."; success_6mo="My book research is organized and searchable. I've written three more chapters. HOA minutes take 20 minutes instead of two hours."; priority="time"; tried_ai="no"; nervous="I just don't want to feel stupid. Every tech thing I try assumes I already know things I don't."; cloud_comfort="nervous"; urgency="exploring"; budget_posture="under_50" },

  @{ name="Barbara"; situation="retired"; comfort="okay"; work="Retired nurse practitioner. I volunteer at a community health fair, run a book club, and I'm on the board of a literacy nonprofit. Also help my daughter with marketing for her Pilates studio."; creates="Health fair handouts, book club discussion guides, nonprofit board reports, social media posts, personal blog posts"; team="solo"; typical_week="No two weeks are the same. Board work comes in waves. Pilates marketing is a few hours a week."; location_today="home"; location_wanted="Home and the coffee shop where my book club meets."; devices="iphone, mac, ipad"; subscriptions="google, ai"; subscriptions_other="Squarespace for my blog"; data_lives="Google Drive for most things. Blog on Squarespace. Photos everywhere."; friction="Content creation across too many contexts. I'm writing a board report one hour, a social media post the next, a blog entry after that."; manual_tasks="1) Creating social media graphics for the Pilates studio. 2) Writing book club discussion questions. 3) Compiling volunteer hours for the nonprofit board."; already_tried="I have a ChatGPT subscription. I use it almost every day. But I want something more tailored."; inbox="zero"; wish="I want each hat I wear to have its own assistant that knows the context."; success_6mo="I'm producing more content with less effort. Each project has its own organized workspace."; priority="peace"; tried_ai="regular"; nervous="Not about privacy - more about quality. I don't want generic stuff."; cloud_comfort="fine"; urgency="month"; budget_posture="50_100" },

  @{ name="Richard"; situation="retired"; comfort="avoid"; work="Retired fire chief. Some consulting on fire safety for commercial buildings. Maybe five clients a year. Also manage my investments and I'm VP of our Rotary chapter."; creates="Fire safety assessment reports, Rotary newsletters, investment tracking spreadsheets"; team="solo"; typical_week="A fire safety inspection takes a full day including the write-up. Rotary is one meeting a week plus the newsletter monthly."; location_today="home"; location_wanted="Home. But my wife wants to travel more and I can't write reports on the road."; devices="pc, iphone"; subscriptions="m365"; data_lives="Everything on the PC. Fire safety reports in Word. Investment tracking in an Excel file I've maintained for 12 years. Rotary stuff in email."; friction="Fire safety reports. Each one is 20-30 pages. I write them from a template but still spend two full days."; manual_tasks="1) Writing fire safety reports from inspection notes. 2) The Rotary newsletter. 3) Updating my investment spreadsheet."; already_tried="Nothing. My daughter keeps telling me to try AI. I've been thinking about it for a year."; inbox="manageable"; wish="I dictate my inspection notes in the car on the way home and a finished report appears in my inbox the next morning."; success_6mo="Reports take one day instead of two. I'm taking two more clients a year. My wife and I booked that river cruise."; priority="money"; tried_ai="no"; nervous="I'm skeptical. Show me it actually works for what I do and I'll believe it."; cloud_comfort="nervous"; urgency="exploring"; budget_posture="50_100" },

  @{ name="Elena"; situation="other"; situation_other="Freelance translator (Spanish/English) and ESL teacher at a community college."; comfort="okay"; work="I translate documents - legal, medical, business - and teach two ESL classes at the community college."; creates="Translated documents, lesson plans, student handouts, invoices, glossaries"; team="solo"; typical_week="Teaching Tuesday and Thursday evenings. Translation deadlines whenever they come in. I prep lessons on weekends."; location_today="home"; location_wanted="Home and the college. Sometimes a library."; devices="mac, iphone"; subscriptions="m365, google"; subscriptions_other="SDL Trados translation memory software"; data_lives="Trados has my translation memories. Lesson plans in Google Drive. Invoices in Word. Client contacts in email and phone."; friction="Translation memory management. Trados is powerful but the interface is from 1998. Also lesson planning is repetitive."; manual_tasks="1) Formatting translated documents to match the original layout. 2) Creating vocabulary handouts each week. 3) Invoicing - I calculate hours manually."; already_tried="I've tried Google Translate and DeepL as starting points. They're okay for simple docs but terrible for legal and medical terminology."; inbox="manageable"; wish="A glossary that builds itself as I work. And lesson materials that adapt based on where my students are."; success_6mo="Translation projects go 30% faster. Lesson prep takes half the time. I have a professional glossary I can reference."; priority="time"; tried_ai="little"; nervous="Translation accuracy. Legal and medical documents can't have errors."; cloud_comfort="fine"; urgency="month"; budget_posture="50_100" },

  @{ name="David"; situation="other"; situation_other="Disabled, work from home as a freelance writer. Limited mobility means I rely heavily on voice and computer."; comfort="comfortable"; work="Freelance content writer. Blog posts, white papers, and case studies for B2B tech companies. All remote."; creates="Blog posts (2-3/week), white papers (1-2/month), case studies, LinkedIn posts for clients, outlines and briefs"; team="solo"; typical_week="Writing Mon-Fri, roughly 6 hours a day. I take frequent breaks. Mornings are my best writing time. Afternoons are client calls, research, and admin."; location_today="home"; location_wanted="Home. My office is set up for my needs."; devices="pc, iphone"; subscriptions="m365, ai, passwords"; subscriptions_other="Dragon NaturallySpeaking, Grammarly"; data_lives="OneDrive has all my writing. Client folders organized by company. A master spreadsheet tracks assignments, deadlines, word counts, and payments."; friction="Research. Before I write anything I need to understand the client's industry. I spend 40% of my time researching and only 60% writing."; manual_tasks="1) Compiling background research for each new piece. 2) Updating my tracking spreadsheet. 3) Reformatting pieces from Word into client CMS formats."; already_tried="I use Claude daily for outlining and research summaries. Game changer. But I want it integrated into my workflow."; inbox="zero"; wish="I want to start each writing project with a complete research brief already done."; success_6mo="I'm writing 50% more pieces per week. Research is instant instead of two hours per article. I've raised my rates."; priority="money"; tried_ai="regular"; nervous="Not about AI. More about finding tools that work well with voice input."; cloud_comfort="fine"; urgency="asap"; budget_posture="100_250"; anything_else="Accessibility matters. Whatever tools you recommend need to work well with voice input and screen magnification. I use Dragon NaturallySpeaking." }
)

Write-Host "Seeding 25 test plans via $Endpoint"
Write-Host "All submissions use _test: true (customer emails suppressed)`n"

for ($i = 0; $i -lt $personas.Count; $i++) {
    $p = $personas[$i]
    $label = "[{0,2}/25]" -f ($i + 1)

    # Build the payload - add test flag and contact email
    $payload = @{}
    foreach ($key in $p.Keys) {
        $payload[$key] = $p[$key]
    }
    $payload["contact"] = "test+$($p.name.ToLower())@alongsideai.ai"
    $payload["_test"] = $true

    $json = $payload | ConvertTo-Json -Depth 3 -Compress

    Write-Host "$label Submitting $($p.name) ($($p.situation))..."

    try {
        $response = Invoke-WebRequest -Uri $Endpoint -Method POST -ContentType "application/json" -Body ([System.Text.Encoding]::UTF8.GetBytes($json)) -UseBasicParsing
        Write-Host "$label   -> $($response.StatusCode) $($response.Content.Substring(0, [Math]::Min(120, $response.Content.Length)))"
    } catch {
        Write-Host "$label   -> FAILED: $($_.Exception.Message)"
    }

    if ($i -lt $personas.Count - 1) {
        Start-Sleep -Seconds 5
    }
}

Write-Host "`nDone. 25 submissions queued for plan generation."
Write-Host "Plans will generate in the background over the next 15-75 minutes."
Write-Host "Check Netlify function logs to monitor progress."
